### ISSUE TITLE
Error when running tutorials after being installed from ROS repositories

### ISSUE THREAD

**Issue by jr-bor** [stonier/rqt_py_trees#12]
When installing the py_trees suite from the ROS repos and trying to run the tutorials I get:
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/rqt_py_trees/rqt_py_trees", line 10, in <module>
    from rqt_py_trees.behaviour_tree import RosBehaviourTree
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_py_trees/__init__.py", line 16, in <module>
    from . import behaviour_tree
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_py_trees/behaviour_tree.py", line 55, in <module>
    from qt_dotgraph.dot_to_qt import DotToQtGenerator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_py_trees/qt_dotgraph/__init__.py", line 21, in <module>
    from . import dot_to_qt
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_py_trees/qt_dotgraph/dot_to_qt.py", line 23, in <module>
    import pygraphviz
ImportError: No module named pygraphviz
```

Fixed with #11 . Until pushed to the repos the package can be cloned and then the dependency can be resolved by running [rosdep](http://docs.ros.org/independent/api/rosdep/html/commands.html) (rosdep install --from-paths (path of package or workspace) --ignore-src --rosdistro=$ROS_DISTRO -y)

**Comment by stonier** [comment]
Closed with PR #11.
